CREATE TABLE public.resume_config_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL DEFAULT auth.uid(),
  resume_id uuid NOT NULL,
  version_no integer NOT NULL,
  version_name text,
  description text,
  milestone_name text,
  source_type text NOT NULL DEFAULT 'manual',
  tags jsonb DEFAULT '[]'::jsonb,
  snapshot jsonb NOT NULL,
  content_hash text,
  base_updated_at timestamptz,
  CONSTRAINT resume_config_versions_pkey PRIMARY KEY (id),
  CONSTRAINT resume_config_versions_resume_id_fkey
    FOREIGN KEY (resume_id) REFERENCES public.resume_config (resume_id) ON DELETE CASCADE,
  CONSTRAINT resume_config_versions_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT resume_config_versions_resume_id_version_no_key
    UNIQUE (resume_id, version_no),
  CONSTRAINT resume_config_versions_source_type_check
    CHECK (source_type IN ('manual', 'autosave', 'restore', 'ai_optimize', 'import')),
  CONSTRAINT resume_config_versions_tags_is_array_check
    CHECK (tags IS NULL OR jsonb_typeof(tags) = 'array'),
  CONSTRAINT resume_config_versions_snapshot_is_object_check
    CHECK (jsonb_typeof(snapshot) = 'object')
);

CREATE OR REPLACE FUNCTION public.set_resume_config_version_no()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  next_version_no integer;
BEGIN
  SELECT coalesce(max(version_no), 0) + 1
  INTO next_version_no
  FROM public.resume_config_versions
  WHERE resume_id = NEW.resume_id;

  NEW.version_no := next_version_no;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.set_resume_config_version_no()
  FROM PUBLIC, anon, authenticated;

CREATE TRIGGER set_resume_config_version_no_trigger
  BEFORE INSERT ON public.resume_config_versions
  FOR EACH ROW EXECUTE FUNCTION public.set_resume_config_version_no();

CREATE TRIGGER update_resume_config_versions_updated_at
  BEFORE UPDATE ON public.resume_config_versions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_resume_config_versions_resume_id
  ON public.resume_config_versions (resume_id);

CREATE INDEX idx_resume_config_versions_user_id
  ON public.resume_config_versions (user_id);

CREATE INDEX idx_resume_config_versions_resume_id_created_at
  ON public.resume_config_versions (resume_id, created_at DESC);

CREATE INDEX idx_resume_config_versions_resume_id_version_no_desc
  ON public.resume_config_versions (resume_id, version_no DESC);

CREATE INDEX idx_resume_config_versions_resume_id_milestone_name
  ON public.resume_config_versions (resume_id, milestone_name)
  WHERE milestone_name IS NOT NULL;

CREATE INDEX idx_resume_config_versions_content_hash
  ON public.resume_config_versions (resume_id, content_hash)
  WHERE content_hash IS NOT NULL;
