CREATE TABLE public.resume_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  template_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid(),
  family_id text NOT NULL,
  based_on_template_id text,
  name text NOT NULL,
  description text,
  visibility text NOT NULL DEFAULT 'private',
  status text NOT NULL DEFAULT 'active',
  manifest jsonb NOT NULL,
  CONSTRAINT resume_templates_pkey PRIMARY KEY (id),
  CONSTRAINT resume_templates_template_id_key UNIQUE (template_id),
  CONSTRAINT resume_templates_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT resume_templates_visibility_check
    CHECK (visibility IN ('private', 'published')),
  CONSTRAINT resume_templates_status_check
    CHECK (status IN ('draft', 'active', 'archived')),
  CONSTRAINT resume_templates_manifest_is_object_check
    CHECK (jsonb_typeof(manifest) = 'object')
);

CREATE INDEX idx_resume_templates_user_id
  ON public.resume_templates (user_id);

CREATE INDEX idx_resume_templates_user_id_updated_at_desc
  ON public.resume_templates (user_id, updated_at DESC);

CREATE INDEX idx_resume_templates_user_id_visibility
  ON public.resume_templates (user_id, visibility);

CREATE TRIGGER update_resume_templates_updated_at
  BEFORE UPDATE ON public.resume_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
