CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA extensions;

CREATE SCHEMA IF NOT EXISTS private;

CREATE TABLE private.backend_operation_metrics (
  bucket_minute timestamptz NOT NULL,
  function_name text NOT NULL,
  operation text NOT NULL,
  outcome text NOT NULL,
  error_code text NOT NULL DEFAULT '',
  request_count bigint NOT NULL DEFAULT 0,
  duration_ms_sum bigint NOT NULL DEFAULT 0,
  duration_ms_max integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  PRIMARY KEY (bucket_minute, function_name, operation, outcome, error_code),
  CONSTRAINT backend_operation_metrics_function_check
    CHECK (function_name ~ '^[a-z][a-z0-9_-]{0,63}$'),
  CONSTRAINT backend_operation_metrics_operation_check
    CHECK (operation ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_operation_metrics_outcome_check
    CHECK (outcome IN ('success', 'client_error', 'server_error')),
  CONSTRAINT backend_operation_metrics_error_code_check
    CHECK (error_code = '' OR error_code ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_operation_metrics_counts_check
    CHECK (
      request_count >= 0
      AND duration_ms_sum >= 0
      AND duration_ms_max >= 0
    )
);

CREATE INDEX backend_operation_metrics_bucket_idx
  ON private.backend_operation_metrics (bucket_minute DESC);

CREATE TABLE private.backend_error_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL,
  function_name text NOT NULL,
  operation text NOT NULL,
  error_code text NOT NULL,
  sql_state text,
  status integer NOT NULL,
  duration_ms integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  CONSTRAINT backend_error_events_function_check
    CHECK (function_name ~ '^[a-z][a-z0-9_-]{0,63}$'),
  CONSTRAINT backend_error_events_operation_check
    CHECK (operation ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_error_events_error_code_check
    CHECK (error_code ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_error_events_sql_state_check
    CHECK (sql_state IS NULL OR sql_state ~ '^[0-9A-Z]{5}$'),
  CONSTRAINT backend_error_events_status_check
    CHECK (status BETWEEN 400 AND 599),
  CONSTRAINT backend_error_events_duration_check
    CHECK (duration_ms >= 0)
);

CREATE INDEX backend_error_events_created_idx
  ON private.backend_error_events (created_at DESC);

CREATE INDEX backend_error_events_code_created_idx
  ON private.backend_error_events (error_code, created_at DESC);

REVOKE ALL ON TABLE private.backend_operation_metrics
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE private.backend_error_events
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE private.backend_error_events_id_seq
  FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE private.backend_operation_metrics
  TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE private.backend_error_events
  TO service_role;
GRANT USAGE, SELECT ON SEQUENCE private.backend_error_events_id_seq
  TO service_role;

CREATE OR REPLACE FUNCTION public.record_backend_operation(
  p_request_id uuid,
  p_function_name text,
  p_operation text,
  p_outcome text,
  p_error_code text,
  p_sql_state text,
  p_status integer,
  p_duration_ms integer
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_bucket timestamptz := pg_catalog.date_trunc('minute', pg_catalog.now());
  v_error_code text := coalesce(p_error_code, '');
BEGIN
  IF p_request_id IS NULL
     OR p_function_name !~ '^[a-z][a-z0-9_-]{0,63}$'
     OR p_operation !~ '^[a-z][a-z0-9_]{0,63}$'
     OR p_outcome NOT IN ('success', 'client_error', 'server_error')
     OR (v_error_code <> '' AND v_error_code !~ '^[a-z][a-z0-9_]{0,63}$')
     OR (p_sql_state IS NOT NULL AND p_sql_state !~ '^[0-9A-Z]{5}$')
     OR p_status < 100
     OR p_status > 599
     OR p_duration_ms < 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid backend operation metric';
  END IF;

  INSERT INTO private.backend_operation_metrics (
    bucket_minute,
    function_name,
    operation,
    outcome,
    error_code,
    request_count,
    duration_ms_sum,
    duration_ms_max
  ) VALUES (
    v_bucket,
    p_function_name,
    p_operation,
    p_outcome,
    v_error_code,
    1,
    p_duration_ms,
    p_duration_ms
  )
  ON CONFLICT (bucket_minute, function_name, operation, outcome, error_code)
  DO UPDATE SET
    request_count = private.backend_operation_metrics.request_count + 1,
    duration_ms_sum = private.backend_operation_metrics.duration_ms_sum + EXCLUDED.duration_ms_sum,
    duration_ms_max = pg_catalog.greatest(
      private.backend_operation_metrics.duration_ms_max,
      EXCLUDED.duration_ms_max
    ),
    updated_at = pg_catalog.now();

  IF p_outcome <> 'success' AND v_error_code <> '' THEN
    INSERT INTO private.backend_error_events (
      request_id,
      function_name,
      operation,
      error_code,
      sql_state,
      status,
      duration_ms
    ) VALUES (
      p_request_id,
      p_function_name,
      p_operation,
      v_error_code,
      p_sql_state,
      p_status,
      p_duration_ms
    );
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.record_backend_operation(uuid, text, text, text, text, text, integer, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_backend_operation(uuid, text, text, text, text, text, integer, integer)
  TO service_role;
