CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault;

-- Best effort for self-hosted Postgres. Supabase-hosted pg_net objects are
-- owned and may be re-granted by supabase_admin after extension setup, so the
-- enforceable API boundary is also pinned in config.toml: net is not an
-- exposed PostgREST schema and no public function accepts an arbitrary URL.
REVOKE USAGE ON SCHEMA net FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL TABLES IN SCHEMA net
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA net
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA net
  FROM PUBLIC, anon, authenticated, service_role;

CREATE TABLE private.backend_maintenance_config (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  cleanup_enabled boolean NOT NULL DEFAULT false,
  edge_jobs_enabled boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT pg_catalog.now()
);

INSERT INTO private.backend_maintenance_config (singleton)
VALUES (true)
ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE private.backend_maintenance_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name text NOT NULL,
  outcome text NOT NULL,
  processed_count integer NOT NULL DEFAULT 0,
  batch_limit_hit boolean NOT NULL DEFAULT false,
  error_code text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz NOT NULL,
  finished_at timestamptz NOT NULL,
  duration_ms integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  CONSTRAINT backend_maintenance_runs_job_check
    CHECK (job_name ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_maintenance_runs_outcome_check
    CHECK (outcome IN ('queued', 'success', 'skipped', 'failed')),
  CONSTRAINT backend_maintenance_runs_count_check
    CHECK (processed_count >= 0),
  CONSTRAINT backend_maintenance_runs_error_check
    CHECK (error_code IS NULL OR error_code ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_maintenance_runs_details_check
    CHECK (pg_catalog.jsonb_typeof(details) = 'object'),
  CONSTRAINT backend_maintenance_runs_time_check
    CHECK (finished_at >= started_at AND duration_ms >= 0)
);

CREATE INDEX backend_maintenance_runs_job_created_idx
  ON private.backend_maintenance_runs (job_name, created_at DESC);
CREATE INDEX backend_maintenance_runs_failed_created_idx
  ON private.backend_maintenance_runs (created_at DESC)
  WHERE outcome = 'failed';

CREATE TABLE private.backend_edge_dispatches (
  request_id bigint PRIMARY KEY CHECK (request_id > 0),
  maintenance_run_id bigint NOT NULL UNIQUE
    REFERENCES private.backend_maintenance_runs (id) ON DELETE CASCADE,
  function_name text NOT NULL,
  state text NOT NULL DEFAULT 'queued',
  status_code integer,
  error_code text,
  dispatched_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  completed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  CONSTRAINT backend_edge_dispatches_function_check
    CHECK (function_name IN ('github-stars-refresh', 'backend-ops-monitor')),
  CONSTRAINT backend_edge_dispatches_state_check
    CHECK (state IN ('queued', 'succeeded', 'failed')),
  CONSTRAINT backend_edge_dispatches_status_check
    CHECK (status_code IS NULL OR status_code BETWEEN 100 AND 599),
  CONSTRAINT backend_edge_dispatches_error_check
    CHECK (error_code IS NULL OR error_code ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_edge_dispatches_completion_check
    CHECK (
      (state = 'queued' AND completed_at IS NULL AND status_code IS NULL AND error_code IS NULL)
      OR (state = 'succeeded' AND completed_at IS NOT NULL
        AND status_code BETWEEN 200 AND 299 AND error_code IS NULL)
      OR (state = 'failed' AND completed_at IS NOT NULL AND error_code IS NOT NULL)
    )
);

CREATE INDEX backend_edge_dispatches_queued_idx
  ON private.backend_edge_dispatches (dispatched_at, request_id)
  WHERE state = 'queued';

CREATE TABLE private.backend_alert_state (
  alert_code text PRIMARY KEY,
  active boolean NOT NULL DEFAULT true,
  consecutive_observations integer NOT NULL DEFAULT 1,
  first_observed_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  last_observed_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  last_notified_at timestamptz,
  resolved_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  CONSTRAINT backend_alert_state_code_check
    CHECK (alert_code ~ '^[a-z][a-z0-9_]{0,63}$'),
  CONSTRAINT backend_alert_state_count_check
    CHECK (consecutive_observations >= 0),
  CONSTRAINT backend_alert_state_resolution_check
    CHECK (
      (active AND resolved_at IS NULL)
      OR (NOT active AND resolved_at IS NOT NULL)
    )
);

CREATE TABLE private.ai_usage_daily_rollups (
  quota_date date NOT NULL,
  action text NOT NULL,
  final_state text NOT NULL,
  request_count bigint NOT NULL DEFAULT 0,
  reserved_credits bigint NOT NULL DEFAULT 0,
  debited_credits bigint NOT NULL DEFAULT 0,
  prompt_tokens bigint NOT NULL DEFAULT 0,
  completion_tokens bigint NOT NULL DEFAULT 0,
  total_tokens bigint NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
  PRIMARY KEY (quota_date, action, final_state),
  CONSTRAINT ai_usage_daily_rollups_state_check
    CHECK (final_state IN ('settled', 'released', 'rejected')),
  CONSTRAINT ai_usage_daily_rollups_counts_check
    CHECK (
      request_count >= 0
      AND reserved_credits >= 0
      AND debited_credits >= 0
      AND prompt_tokens >= 0
      AND completion_tokens >= 0
      AND total_tokens >= 0
    )
);

REVOKE ALL ON TABLE private.backend_maintenance_config
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE private.backend_maintenance_runs
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE private.backend_edge_dispatches
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE private.backend_alert_state
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE private.ai_usage_daily_rollups
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE private.backend_maintenance_runs_id_seq
  FROM PUBLIC, anon, authenticated, service_role;

ALTER TABLE public.resume_share_rate_limits
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT pg_catalog.now();
ALTER TABLE public.resume_share_owner_rate_limits
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT pg_catalog.now();

DROP TRIGGER IF EXISTS set_resume_share_rate_limits_updated_at
  ON public.resume_share_rate_limits;
CREATE TRIGGER set_resume_share_rate_limits_updated_at
  BEFORE UPDATE ON public.resume_share_rate_limits
  FOR EACH ROW EXECUTE FUNCTION public.set_resume_comment_updated_at();

DROP TRIGGER IF EXISTS set_resume_share_owner_rate_limits_updated_at
  ON public.resume_share_owner_rate_limits;
CREATE TRIGGER set_resume_share_owner_rate_limits_updated_at
  BEFORE UPDATE ON public.resume_share_owner_rate_limits
  FOR EACH ROW EXECUTE FUNCTION public.set_resume_comment_updated_at();

CREATE INDEX resume_comment_requests_completed_cleanup_idx
  ON public.resume_comment_requests (completed_at, actor_key, request_id)
  WHERE completed_at IS NOT NULL;
CREATE INDEX resume_comment_requests_incomplete_cleanup_idx
  ON public.resume_comment_requests (created_at, actor_key, request_id)
  WHERE completed_at IS NULL AND response IS NULL;
CREATE INDEX resume_comment_rate_limits_cleanup_idx
  ON public.resume_comment_rate_limits (updated_at, bucket_key);
CREATE INDEX resume_share_rate_limits_cleanup_idx
  ON public.resume_share_rate_limits (updated_at, share_id, key_hash);
CREATE INDEX resume_share_owner_rate_limits_cleanup_idx
  ON public.resume_share_owner_rate_limits (updated_at, user_id);
CREATE INDEX resume_comment_collaboration_sessions_expiry_idx
  ON public.resume_comment_collaboration_sessions (expires_at, session_id);
CREATE INDEX resume_comment_collaboration_sessions_revoked_idx
  ON public.resume_comment_collaboration_sessions (revoked_at, session_id)
  WHERE revoked_at IS NOT NULL;
CREATE INDEX resume_comment_collaboration_members_expiry_idx
  ON public.resume_comment_collaboration_members (expires_at, session_id, user_id);
CREATE INDEX resume_comment_collaboration_members_revoked_idx
  ON public.resume_comment_collaboration_members (revoked_at, session_id, user_id)
  WHERE revoked_at IS NOT NULL;
CREATE INDEX ai_credit_requests_finalized_cleanup_idx
  ON public.ai_credit_requests (finalized_at, request_id)
  WHERE state <> 'pending';

CREATE OR REPLACE FUNCTION private.preview_backend_transient_cleanup_v1(
  p_batch_size integer DEFAULT 1000
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_now timestamptz := pg_catalog.now();
  v_result jsonb;
BEGIN
  IF p_batch_size < 100 OR p_batch_size > 5000 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'batch size must be between 100 and 5000';
  END IF;

  SELECT pg_catalog.jsonb_build_object(
    'commentRequests', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM public.resume_comment_requests AS requests
      WHERE (requests.completed_at IS NOT NULL
          AND requests.completed_at < v_now - interval '48 hours')
         OR (requests.completed_at IS NULL
          AND requests.response IS NULL
          AND requests.created_at < v_now - interval '48 hours')
    )),
    'commentRateLimits', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM public.resume_comment_rate_limits AS buckets
      WHERE buckets.updated_at < v_now - interval '48 hours'
        AND buckets.window_started_at
          + pg_catalog.make_interval(secs => buckets.window_seconds) < v_now
        AND (buckets.blocked_until IS NULL OR buckets.blocked_until < v_now)
    )),
    'shareRateLimits', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM public.resume_share_rate_limits AS buckets
      WHERE buckets.updated_at < v_now - interval '48 hours'
        AND buckets.window_started_at < v_now - interval '48 hours'
        AND (buckets.blocked_until IS NULL OR buckets.blocked_until < v_now)
    )),
    'shareOwnerRateLimits', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM public.resume_share_owner_rate_limits AS buckets
      WHERE buckets.updated_at < v_now - interval '48 hours'
        AND buckets.window_started_at < v_now - interval '48 hours'
        AND (buckets.blocked_until IS NULL OR buckets.blocked_until < v_now)
    )),
    'collaborationSessions', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM public.resume_comment_collaboration_sessions AS sessions
      WHERE (
        sessions.expires_at < v_now - interval '24 hours'
        OR sessions.revoked_at < v_now - interval '24 hours'
      )
        AND NOT EXISTS (
          SELECT 1
          FROM public.resume_comment_collaboration_members AS members
          WHERE members.session_id = sessions.session_id
        )
    )),
    'collaborationMembers', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM public.resume_comment_collaboration_members AS members
      WHERE members.expires_at < v_now - interval '24 hours'
         OR members.revoked_at < v_now - interval '24 hours'
    )),
    'aiFinalizedRequests', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM public.ai_credit_requests AS requests
      WHERE requests.state <> 'pending'
        AND requests.finalized_at < v_now - interval '180 days'
    )),
    'backendErrorEvents', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM private.backend_error_events AS events
      WHERE events.created_at < v_now - interval '7 days'
    )),
    'backendOperationMetrics', least(p_batch_size, (
      SELECT pg_catalog.count(*)::integer
      FROM private.backend_operation_metrics AS metrics
      WHERE metrics.bucket_minute < v_now - interval '30 days'
    ))
  ) INTO v_result;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION private.cleanup_backend_transient_data_v1(
  p_batch_size integer DEFAULT 1000
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
SET lock_timeout = '2s'
SET statement_timeout = '30s'
AS $$
DECLARE
  v_started_at timestamptz := pg_catalog.clock_timestamp();
  v_now timestamptz := pg_catalog.now();
  v_enabled boolean;
  v_count integer;
  v_total integer := 0;
  v_batch_limit_hit boolean := false;
  v_counts jsonb := '{}'::jsonb;
  v_ai_request_ids uuid[];
  v_error_code text;
  v_duration integer;
BEGIN
  IF p_batch_size < 100 OR p_batch_size > 5000 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'batch size must be between 100 and 5000';
  END IF;

  SELECT config.cleanup_enabled
  INTO v_enabled
  FROM private.backend_maintenance_config AS config
  WHERE config.singleton;

  IF NOT coalesce(v_enabled, false) THEN
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, started_at, finished_at, duration_ms
    ) VALUES (
      'transient_cleanup', 'skipped', v_started_at,
      pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'skipped', 'reason', 'disabled');
  END IF;

  IF NOT pg_catalog.pg_try_advisory_xact_lock(
    pg_catalog.hashtextextended('resume-backend-transient-cleanup-v1', 0)
  ) THEN
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, started_at, finished_at, duration_ms
    ) VALUES (
      'transient_cleanup', 'skipped', v_started_at,
      pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'skipped', 'reason', 'already_running');
  END IF;

  BEGIN
    WITH candidates AS (
      SELECT requests.ctid
      FROM public.resume_comment_requests AS requests
      WHERE (requests.completed_at IS NOT NULL
          AND requests.completed_at < v_now - interval '48 hours')
         OR (requests.completed_at IS NULL
          AND requests.response IS NULL
          AND requests.created_at < v_now - interval '48 hours')
      ORDER BY coalesce(requests.completed_at, requests.created_at), requests.request_id
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM public.resume_comment_requests AS requests
    USING candidates
    WHERE requests.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('commentRequests', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT buckets.ctid
      FROM public.resume_comment_rate_limits AS buckets
      WHERE buckets.updated_at < v_now - interval '48 hours'
        AND buckets.window_started_at
          + pg_catalog.make_interval(secs => buckets.window_seconds) < v_now
        AND (buckets.blocked_until IS NULL OR buckets.blocked_until < v_now)
      ORDER BY buckets.updated_at, buckets.bucket_key
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM public.resume_comment_rate_limits AS buckets
    USING candidates
    WHERE buckets.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('commentRateLimits', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT buckets.ctid
      FROM public.resume_share_rate_limits AS buckets
      WHERE buckets.updated_at < v_now - interval '48 hours'
        AND buckets.window_started_at < v_now - interval '48 hours'
        AND (buckets.blocked_until IS NULL OR buckets.blocked_until < v_now)
      ORDER BY buckets.updated_at, buckets.share_id, buckets.key_hash
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM public.resume_share_rate_limits AS buckets
    USING candidates
    WHERE buckets.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('shareRateLimits', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT buckets.ctid
      FROM public.resume_share_owner_rate_limits AS buckets
      WHERE buckets.updated_at < v_now - interval '48 hours'
        AND buckets.window_started_at < v_now - interval '48 hours'
        AND (buckets.blocked_until IS NULL OR buckets.blocked_until < v_now)
      ORDER BY buckets.updated_at, buckets.user_id
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM public.resume_share_owner_rate_limits AS buckets
    USING candidates
    WHERE buckets.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('shareOwnerRateLimits', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT members.ctid
      FROM public.resume_comment_collaboration_members AS members
      WHERE members.expires_at < v_now - interval '24 hours'
         OR members.revoked_at < v_now - interval '24 hours'
      ORDER BY coalesce(members.revoked_at, members.expires_at), members.session_id, members.user_id
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM public.resume_comment_collaboration_members AS members
    USING candidates
    WHERE members.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('collaborationMembers', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT sessions.ctid
      FROM public.resume_comment_collaboration_sessions AS sessions
      WHERE (
        sessions.expires_at < v_now - interval '24 hours'
        OR sessions.revoked_at < v_now - interval '24 hours'
      )
        AND NOT EXISTS (
          SELECT 1
          FROM public.resume_comment_collaboration_members AS members
          WHERE members.session_id = sessions.session_id
        )
      ORDER BY coalesce(sessions.revoked_at, sessions.expires_at), sessions.session_id
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM public.resume_comment_collaboration_sessions AS sessions
    USING candidates
    WHERE sessions.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('collaborationSessions', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    SELECT pg_catalog.array_agg(candidates.request_id)
    INTO v_ai_request_ids
    FROM (
      SELECT requests.request_id
      FROM public.ai_credit_requests AS requests
      WHERE requests.state <> 'pending'
        AND requests.finalized_at < v_now - interval '180 days'
      ORDER BY requests.finalized_at, requests.request_id
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    ) AS candidates;

    v_count := coalesce(pg_catalog.cardinality(v_ai_request_ids), 0);
    IF v_count > 0 THEN
      INSERT INTO private.ai_usage_daily_rollups (
        quota_date,
        action,
        final_state,
        request_count,
        reserved_credits,
        debited_credits,
        prompt_tokens,
        completion_tokens,
        total_tokens
      )
      SELECT
        requests.quota_date,
        requests.action,
        requests.state,
        pg_catalog.count(*),
        pg_catalog.sum(requests.reserved_cost),
        pg_catalog.sum(requests.quota_debited),
        pg_catalog.sum(coalesce(requests.prompt_tokens, 0)),
        pg_catalog.sum(coalesce(requests.completion_tokens, 0)),
        pg_catalog.sum(coalesce(requests.total_tokens, 0))
      FROM public.ai_credit_requests AS requests
      WHERE requests.request_id = ANY(v_ai_request_ids)
      GROUP BY requests.quota_date, requests.action, requests.state
      ON CONFLICT (quota_date, action, final_state) DO UPDATE
      SET request_count = private.ai_usage_daily_rollups.request_count + EXCLUDED.request_count,
          reserved_credits = private.ai_usage_daily_rollups.reserved_credits + EXCLUDED.reserved_credits,
          debited_credits = private.ai_usage_daily_rollups.debited_credits + EXCLUDED.debited_credits,
          prompt_tokens = private.ai_usage_daily_rollups.prompt_tokens + EXCLUDED.prompt_tokens,
          completion_tokens = private.ai_usage_daily_rollups.completion_tokens + EXCLUDED.completion_tokens,
          total_tokens = private.ai_usage_daily_rollups.total_tokens + EXCLUDED.total_tokens,
          updated_at = pg_catalog.now();

      DELETE FROM public.ai_credit_requests AS requests
      WHERE requests.request_id = ANY(v_ai_request_ids);
    END IF;
    v_counts := v_counts || pg_catalog.jsonb_build_object('aiFinalizedRequests', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT events.ctid
      FROM private.backend_error_events AS events
      WHERE events.created_at < v_now - interval '7 days'
      ORDER BY events.created_at, events.id
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM private.backend_error_events AS events
    USING candidates
    WHERE events.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('backendErrorEvents', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT metrics.ctid
      FROM private.backend_operation_metrics AS metrics
      WHERE metrics.bucket_minute < v_now - interval '30 days'
      ORDER BY metrics.bucket_minute
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM private.backend_operation_metrics AS metrics
    USING candidates
    WHERE metrics.ctid = candidates.ctid;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_counts := v_counts || pg_catalog.jsonb_build_object('backendOperationMetrics', v_count);
    v_total := v_total + v_count;
    v_batch_limit_hit := v_batch_limit_hit OR v_count = p_batch_size;

    WITH candidates AS (
      SELECT runs.ctid
      FROM private.backend_maintenance_runs AS runs
      WHERE runs.created_at < v_now - interval '90 days'
      ORDER BY runs.created_at, runs.id
      LIMIT p_batch_size
      FOR UPDATE SKIP LOCKED
    )
    DELETE FROM private.backend_maintenance_runs AS runs
    USING candidates
    WHERE runs.ctid = candidates.ctid;

    DELETE FROM private.backend_alert_state AS alerts
    WHERE NOT alerts.active
      AND alerts.updated_at < v_now - interval '90 days';

    WITH candidates AS (
      SELECT details.ctid
      FROM cron.job_run_details AS details
      WHERE details.end_time < v_now - interval '7 days'
      ORDER BY details.end_time, details.runid
      LIMIT p_batch_size
    )
    DELETE FROM cron.job_run_details AS details
    USING candidates
    WHERE details.ctid = candidates.ctid;
  EXCEPTION
  WHEN lock_not_available THEN
    v_error_code := 'lock_timeout';
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, processed_count, error_code,
      started_at, finished_at, duration_ms
    ) VALUES (
      'transient_cleanup', 'skipped', 0, v_error_code,
      v_started_at, pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'skipped', 'errorCode', v_error_code);
  WHEN query_canceled THEN
    v_error_code := 'statement_timeout';
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, processed_count, error_code,
      started_at, finished_at, duration_ms
    ) VALUES (
      'transient_cleanup', 'failed', 0, v_error_code,
      v_started_at, pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'failed', 'errorCode', v_error_code);
  WHEN OTHERS THEN
    v_error_code := 'maintenance_failed';
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, processed_count, error_code,
      started_at, finished_at, duration_ms
    ) VALUES (
      'transient_cleanup', 'failed', 0, v_error_code,
      v_started_at, pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'failed', 'errorCode', v_error_code);
  END;

  v_duration := greatest(
    0,
    pg_catalog.round(
      extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
    )::integer
  );
  INSERT INTO private.backend_maintenance_runs (
    job_name, outcome, processed_count, batch_limit_hit, details,
    started_at, finished_at, duration_ms
  ) VALUES (
    'transient_cleanup', 'success', v_total, v_batch_limit_hit, v_counts,
    v_started_at, pg_catalog.clock_timestamp(), v_duration
  );
  RETURN pg_catalog.jsonb_build_object(
    'outcome', 'success',
    'processed', v_total,
    'batchLimitHit', v_batch_limit_hit,
    'counts', v_counts,
    'durationMs', v_duration
  );
END;
$$;

CREATE OR REPLACE FUNCTION private.run_ai_reconciliation_job_v1(
  p_limit integer DEFAULT 200
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
SET lock_timeout = '2s'
SET statement_timeout = '30s'
AS $$
DECLARE
  v_started_at timestamptz := pg_catalog.clock_timestamp();
  v_result jsonb;
  v_processed integer := 0;
  v_error_code text;
  v_duration integer;
BEGIN
  BEGIN
    v_result := public.reconcile_expired_ai_credit_requests(p_limit);
    v_processed := coalesce((v_result ->> 'processed')::integer, 0);
  EXCEPTION
  WHEN lock_not_available THEN
    v_error_code := 'lock_timeout';
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, error_code, started_at, finished_at, duration_ms
    ) VALUES (
      'ai_reconciliation', 'skipped', v_error_code, v_started_at,
      pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'skipped', 'errorCode', v_error_code);
  WHEN query_canceled THEN
    v_error_code := 'statement_timeout';
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, error_code, started_at, finished_at, duration_ms
    ) VALUES (
      'ai_reconciliation', 'failed', v_error_code, v_started_at,
      pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'failed', 'errorCode', v_error_code);
  WHEN OTHERS THEN
    v_error_code := 'ai_reconciliation_failed';
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, error_code, started_at, finished_at, duration_ms
    ) VALUES (
      'ai_reconciliation', 'failed', v_error_code, v_started_at,
      pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'failed', 'errorCode', v_error_code);
  END;

  v_duration := greatest(
    0,
    pg_catalog.round(
      extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
    )::integer
  );
  INSERT INTO private.backend_maintenance_runs (
    job_name, outcome, processed_count, batch_limit_hit,
    started_at, finished_at, duration_ms
  ) VALUES (
    'ai_reconciliation', 'success', v_processed, v_processed = p_limit,
    v_started_at, pg_catalog.clock_timestamp(), v_duration
  );
  RETURN pg_catalog.jsonb_build_object(
    'outcome', 'success',
    'processed', v_processed,
    'result', v_result,
    'durationMs', v_duration
  );
END;
$$;

CREATE OR REPLACE FUNCTION private.set_backend_maintenance_flags_v1(
  p_cleanup_enabled boolean,
  p_edge_jobs_enabled boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_project_url text;
  v_maintenance_token text;
BEGIN
  IF p_edge_jobs_enabled THEN
    SELECT secrets.decrypted_secret
    INTO v_project_url
    FROM vault.decrypted_secrets AS secrets
    WHERE secrets.name = 'resume_backend_project_url';

    SELECT secrets.decrypted_secret
    INTO v_maintenance_token
    FROM vault.decrypted_secrets AS secrets
    WHERE secrets.name = 'resume_backend_maintenance_token';

    IF v_project_url IS NULL
       OR v_maintenance_token IS NULL
       OR v_project_url !~ '^https://[a-z0-9-]+\.supabase\.co/?$'
       OR pg_catalog.length(v_maintenance_token) < 32 THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'backend edge secrets are not configured';
    END IF;
  END IF;

  UPDATE private.backend_maintenance_config
  SET cleanup_enabled = p_cleanup_enabled,
      edge_jobs_enabled = p_edge_jobs_enabled,
      updated_at = pg_catalog.now()
  WHERE singleton;
END;
$$;

CREATE OR REPLACE FUNCTION private.invoke_backend_edge_job_v1(
  p_function_name text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
SET statement_timeout = '15s'
AS $$
DECLARE
  v_started_at timestamptz := pg_catalog.clock_timestamp();
  v_enabled boolean;
  v_project_url text;
  v_maintenance_token text;
  v_request_id bigint;
  v_duration integer;
  v_job_name text;
  v_maintenance_run_id bigint;
  v_sql_state text;
  v_error_code text;
BEGIN
  IF p_function_name NOT IN ('github-stars-refresh', 'backend-ops-monitor') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'unsupported backend edge job';
  END IF;
  v_job_name := CASE p_function_name
    WHEN 'github-stars-refresh' THEN 'github_refresh_dispatch'
    ELSE 'ops_monitor_dispatch'
  END;

  SELECT config.edge_jobs_enabled
  INTO v_enabled
  FROM private.backend_maintenance_config AS config
  WHERE config.singleton;
  IF NOT coalesce(v_enabled, false) THEN
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, started_at, finished_at, duration_ms
    ) VALUES (
      v_job_name, 'skipped', v_started_at,
      pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'skipped', 'reason', 'disabled');
  END IF;

  BEGIN
    SELECT secrets.decrypted_secret
    INTO STRICT v_project_url
    FROM vault.decrypted_secrets AS secrets
    WHERE secrets.name = 'resume_backend_project_url';

    SELECT secrets.decrypted_secret
    INTO STRICT v_maintenance_token
    FROM vault.decrypted_secrets AS secrets
    WHERE secrets.name = 'resume_backend_maintenance_token';

    IF v_project_url !~ '^https://[a-z0-9-]+\.supabase\.co/?$'
       OR pg_catalog.length(v_maintenance_token) < 32 THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid backend edge secrets';
    END IF;

    SELECT net.http_post(
      url => pg_catalog.rtrim(v_project_url, '/') || '/functions/v1/' || p_function_name,
      body => '{}'::jsonb,
      headers => pg_catalog.jsonb_build_object(
        'Authorization', 'Bearer ' || v_maintenance_token,
        'Content-Type', 'application/json'
      ),
      timeout_milliseconds => 10000
    ) INTO v_request_id;
  EXCEPTION WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS v_sql_state = RETURNED_SQLSTATE;
    v_error_code := CASE
      WHEN v_sql_state = 'P0002' THEN 'maintenance_secret_missing'
      ELSE 'edge_dispatch_failed'
    END;
    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
      )::integer
    );
    INSERT INTO private.backend_maintenance_runs (
      job_name, outcome, error_code, started_at, finished_at, duration_ms
    ) VALUES (
      v_job_name, 'failed', v_error_code, v_started_at,
      pg_catalog.clock_timestamp(), v_duration
    );
    RETURN pg_catalog.jsonb_build_object('outcome', 'failed', 'errorCode', v_error_code);
  END;

  v_duration := greatest(
    0,
    pg_catalog.round(
      extract(epoch FROM (pg_catalog.clock_timestamp() - v_started_at)) * 1000
    )::integer
  );
  INSERT INTO private.backend_maintenance_runs (
    job_name, outcome, processed_count, details,
    started_at, finished_at, duration_ms
  ) VALUES (
    v_job_name, 'queued', 0,
    pg_catalog.jsonb_build_object('requestId', v_request_id),
    v_started_at, pg_catalog.clock_timestamp(), v_duration
  ) RETURNING id INTO v_maintenance_run_id;

  INSERT INTO private.backend_edge_dispatches (
    request_id, maintenance_run_id, function_name, dispatched_at
  ) VALUES (
    v_request_id, v_maintenance_run_id, p_function_name, v_started_at
  );

  RETURN pg_catalog.jsonb_build_object('outcome', 'queued', 'requestId', v_request_id);
END;
$$;

CREATE OR REPLACE FUNCTION private.reconcile_backend_edge_dispatches_v1(
  p_limit integer DEFAULT 200
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
SET lock_timeout = '2s'
SET statement_timeout = '30s'
AS $$
DECLARE
  v_now timestamptz := pg_catalog.now();
  v_dispatch record;
  v_state text;
  v_error_code text;
  v_completed integer := 0;
  v_succeeded integer := 0;
  v_failed integer := 0;
  v_duration integer;
BEGIN
  IF p_limit < 1 OR p_limit > 1000 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'limit must be between 1 and 1000';
  END IF;

  IF NOT pg_catalog.pg_try_advisory_xact_lock(
    pg_catalog.hashtextextended('resume-backend-edge-dispatch-reconcile-v1', 0)
  ) THEN
    RETURN pg_catalog.jsonb_build_object('outcome', 'skipped', 'reason', 'already_running');
  END IF;

  FOR v_dispatch IN
    SELECT
      dispatches.request_id,
      dispatches.maintenance_run_id,
      dispatches.dispatched_at,
      responses.id AS response_id,
      responses.status_code,
      responses.timed_out,
      responses.error_msg,
      responses.created AS response_created_at,
      queued_requests.id AS queued_request_id
    FROM private.backend_edge_dispatches AS dispatches
    LEFT JOIN net._http_response AS responses
      ON responses.id = dispatches.request_id
    LEFT JOIN net.http_request_queue AS queued_requests
      ON queued_requests.id = dispatches.request_id
    WHERE dispatches.state = 'queued'
      AND (
        responses.id IS NOT NULL
        OR (
          queued_requests.id IS NULL
          AND dispatches.dispatched_at < v_now - interval '2 minutes'
        )
      )
    ORDER BY dispatches.dispatched_at, dispatches.request_id
    LIMIT p_limit
    FOR UPDATE OF dispatches SKIP LOCKED
  LOOP
    IF v_dispatch.response_id IS NULL THEN
      v_state := 'failed';
      v_error_code := 'edge_response_missing';
    ELSIF coalesce(v_dispatch.timed_out, false) THEN
      v_state := 'failed';
      v_error_code := 'edge_response_timeout';
    ELSIF v_dispatch.error_msg IS NOT NULL THEN
      v_state := 'failed';
      v_error_code := 'edge_transport_error';
    ELSIF v_dispatch.status_code BETWEEN 200 AND 299 THEN
      v_state := 'succeeded';
      v_error_code := NULL;
    ELSE
      v_state := 'failed';
      v_error_code := 'edge_http_status';
    END IF;

    UPDATE private.backend_edge_dispatches AS dispatches
    SET state = v_state,
        status_code = CASE
          WHEN v_dispatch.status_code BETWEEN 100 AND 599
            THEN v_dispatch.status_code
          ELSE NULL
        END,
        error_code = v_error_code,
        completed_at = coalesce(v_dispatch.response_created_at, v_now),
        updated_at = v_now
    WHERE dispatches.request_id = v_dispatch.request_id;

    v_duration := greatest(
      0,
      pg_catalog.round(
        extract(epoch FROM (
          coalesce(v_dispatch.response_created_at, v_now) - v_dispatch.dispatched_at
        )) * 1000
      )::integer
    );
    UPDATE private.backend_maintenance_runs AS runs
    SET outcome = CASE WHEN v_state = 'succeeded' THEN 'success' ELSE 'failed' END,
        processed_count = CASE WHEN v_state = 'succeeded' THEN 1 ELSE 0 END,
        error_code = v_error_code,
        details = pg_catalog.jsonb_build_object(
          'requestId', v_dispatch.request_id,
          'statusCode', CASE
            WHEN v_dispatch.status_code BETWEEN 100 AND 599
              THEN v_dispatch.status_code
            ELSE NULL
          END
        ),
        finished_at = coalesce(v_dispatch.response_created_at, v_now),
        duration_ms = v_duration
    WHERE runs.id = v_dispatch.maintenance_run_id;

    v_completed := v_completed + 1;
    IF v_state = 'succeeded' THEN
      v_succeeded := v_succeeded + 1;
    ELSE
      v_failed := v_failed + 1;
    END IF;
  END LOOP;

  RETURN pg_catalog.jsonb_build_object(
    'outcome', 'success',
    'processed', v_completed,
    'succeeded', v_succeeded,
    'failed', v_failed,
    'batchLimitHit', v_completed = p_limit
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.evaluate_backend_ops_alerts_v1(
  p_window_minutes integer DEFAULT 15
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_now timestamptz := pg_catalog.now();
  v_cutoff timestamptz;
  v_alerts jsonb := '[]'::jsonb;
  v_alert jsonb;
  v_codes text[] := ARRAY[]::text[];
  v_notification_codes text[] := ARRAY[]::text[];
  v_ai_failures bigint := 0;
  v_comment_total bigint := 0;
  v_comment_failures bigint := 0;
  v_comment_deadlocks bigint := 0;
  v_share_total bigint := 0;
  v_share_failures bigint := 0;
  v_maintenance_failures bigint := 0;
  v_maintenance_failure_streak boolean := false;
  v_cron_failures bigint := 0;
  v_cron_failure_streak boolean := false;
  v_stale_edge_dispatches bigint := 0;
  v_expired_pending bigint := 0;
  v_cleanup_enabled boolean := false;
  v_cleanup_backlog boolean := false;
  v_github_fetched_at timestamptz;
  v_github_failures integer;
  v_code text;
BEGIN
  IF p_window_minutes < 5 OR p_window_minutes > 1440 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'window must be between 5 and 1440 minutes';
  END IF;
  v_cutoff := v_now - pg_catalog.make_interval(mins => p_window_minutes);

  SELECT
    coalesce(pg_catalog.sum(metrics.request_count) FILTER (
      WHERE metrics.error_code = 'quota_finalization_failed'
    ), 0)
  INTO v_ai_failures
  FROM private.backend_operation_metrics AS metrics
  WHERE metrics.bucket_minute >= v_cutoff
    AND metrics.function_name = 'llm-proxy';

  SELECT
    coalesce(pg_catalog.sum(metrics.request_count), 0),
    coalesce(pg_catalog.sum(metrics.request_count) FILTER (
      WHERE metrics.outcome = 'server_error'
         OR metrics.error_code = 'database_deadlock'
    ), 0),
    coalesce(pg_catalog.sum(metrics.request_count) FILTER (
      WHERE metrics.error_code = 'database_deadlock'
    ), 0)
  INTO v_comment_total, v_comment_failures, v_comment_deadlocks
  FROM private.backend_operation_metrics AS metrics
  WHERE metrics.bucket_minute >= v_cutoff
    AND metrics.function_name = 'resume-comments';

  SELECT
    coalesce(pg_catalog.sum(metrics.request_count), 0),
    coalesce(pg_catalog.sum(metrics.request_count) FILTER (
      WHERE metrics.outcome = 'server_error'
    ), 0)
  INTO v_share_total, v_share_failures
  FROM private.backend_operation_metrics AS metrics
  WHERE metrics.bucket_minute >= v_cutoff
    AND metrics.function_name = 'resume-share'
    AND metrics.operation = 'share_access';

  SELECT pg_catalog.count(*)
  INTO v_maintenance_failures
  FROM private.backend_maintenance_runs AS runs
  WHERE runs.created_at >= v_cutoff
    AND runs.outcome = 'failed';

  SELECT EXISTS (
    SELECT 1
    FROM (
      SELECT
        ranked.job_name,
        pg_catalog.count(*) AS observation_count,
        pg_catalog.bool_and(ranked.outcome = 'failed') AS all_failed
      FROM (
        SELECT
          runs.job_name,
          runs.outcome,
          pg_catalog.row_number() OVER (
            PARTITION BY runs.job_name
            ORDER BY runs.created_at DESC, runs.id DESC
          ) AS observation_rank
        FROM private.backend_maintenance_runs AS runs
      ) AS ranked
      WHERE ranked.observation_rank <= 3
      GROUP BY ranked.job_name
    ) AS streaks
    WHERE streaks.observation_count = 3
      AND streaks.all_failed
  ) INTO v_maintenance_failure_streak;

  SELECT pg_catalog.count(*)
  INTO v_cron_failures
  FROM cron.job_run_details AS details
  JOIN cron.job AS jobs ON jobs.jobid = details.jobid
  WHERE details.start_time >= v_cutoff
    AND details.status <> 'succeeded'
    AND jobs.jobname IN (
      'resume-backend-ai-reconcile',
      'resume-backend-edge-dispatch-reconcile',
      'resume-backend-transient-cleanup',
      'resume-backend-transient-catchup',
      'resume-backend-ops-monitor',
      'resume-github-stars-refresh'
    );

  SELECT EXISTS (
    SELECT 1
    FROM (
      SELECT
        ranked.job_name,
        pg_catalog.count(*) AS observation_count,
        pg_catalog.bool_and(ranked.status <> 'succeeded') AS all_failed
      FROM (
        SELECT
          jobs.jobname AS job_name,
          details.status,
          pg_catalog.row_number() OVER (
            PARTITION BY jobs.jobname
            ORDER BY details.start_time DESC, details.runid DESC
          ) AS observation_rank
        FROM cron.job_run_details AS details
        JOIN cron.job AS jobs ON jobs.jobid = details.jobid
        WHERE details.end_time IS NOT NULL
          AND jobs.jobname IN (
            'resume-backend-ai-reconcile',
            'resume-backend-edge-dispatch-reconcile',
            'resume-backend-transient-cleanup',
            'resume-backend-transient-catchup',
            'resume-backend-ops-monitor',
            'resume-github-stars-refresh'
          )
      ) AS ranked
      WHERE ranked.observation_rank <= 3
      GROUP BY ranked.job_name
    ) AS streaks
    WHERE streaks.observation_count = 3
      AND streaks.all_failed
  ) INTO v_cron_failure_streak;

  SELECT pg_catalog.count(*)
  INTO v_stale_edge_dispatches
  FROM private.backend_edge_dispatches AS dispatches
  WHERE dispatches.state = 'queued'
    AND dispatches.dispatched_at < v_now - interval '2 minutes';

  SELECT pg_catalog.count(*)
  INTO v_expired_pending
  FROM public.ai_credit_requests AS requests
  WHERE requests.state = 'pending'
    AND requests.expires_at < v_now - interval '5 minutes';

  SELECT config.cleanup_enabled
  INTO v_cleanup_enabled
  FROM private.backend_maintenance_config AS config
  WHERE config.singleton;

  IF v_cleanup_enabled THEN
    SELECT pg_catalog.count(*) = 3
      AND pg_catalog.bool_and(recent.outcome = 'success' AND recent.batch_limit_hit)
    INTO v_cleanup_backlog
    FROM (
      SELECT runs.outcome, runs.batch_limit_hit
      FROM private.backend_maintenance_runs AS runs
      WHERE runs.job_name = 'transient_cleanup'
      ORDER BY runs.created_at DESC, runs.id DESC
      LIMIT 3
    ) AS recent;
    v_cleanup_backlog := coalesce(v_cleanup_backlog, false);
  END IF;

  SELECT cache.fetched_at, cache.consecutive_failures
  INTO v_github_fetched_at, v_github_failures
  FROM public.github_stars AS cache
  WHERE cache.repo = '506-fetl/resume';

  IF v_ai_failures > 0 THEN
    v_alerts := v_alerts || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'code', 'ai_quota_finalization_failed', 'severity', 'critical',
      'count', v_ai_failures, 'windowMinutes', p_window_minutes
    ));
  END IF;
  IF v_comment_deadlocks > 0
     OR v_comment_failures >= 3
     OR (v_comment_total >= 20 AND v_comment_failures * 100 >= v_comment_total * 5) THEN
    v_alerts := v_alerts || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'code', 'comment_transaction_failures', 'severity', 'high',
      'count', v_comment_failures, 'deadlocks', v_comment_deadlocks,
      'total', v_comment_total, 'windowMinutes', p_window_minutes
    ));
  END IF;
  IF v_share_failures >= 3
     OR (v_share_total >= 20 AND v_share_failures * 100 >= v_share_total * 5) THEN
    v_alerts := v_alerts || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'code', 'share_read_failures', 'severity', 'high',
      'count', v_share_failures, 'total', v_share_total,
      'windowMinutes', p_window_minutes
    ));
  END IF;
  IF v_maintenance_failure_streak
     OR v_cron_failure_streak
     OR v_stale_edge_dispatches > 0
     OR v_expired_pending > 0
     OR v_cleanup_backlog THEN
    v_alerts := v_alerts || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'code', 'backend_maintenance_failure', 'severity', 'critical',
      'failedRuns', v_maintenance_failures,
      'consecutiveFailureStreak', v_maintenance_failure_streak,
      'failedCronRuns', v_cron_failures,
      'consecutiveCronFailureStreak', v_cron_failure_streak,
      'staleEdgeDispatches', v_stale_edge_dispatches,
      'expiredPendingAiRequests', v_expired_pending,
      'cleanupBacklog', v_cleanup_backlog,
      'windowMinutes', p_window_minutes
    ));
  END IF;
  IF v_github_fetched_at IS NULL
     OR v_github_fetched_at < v_now - interval '24 hours'
     OR coalesce(v_github_failures, 0) >= 3 THEN
    v_alerts := v_alerts || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'code', 'github_cache_stale', 'severity', 'warning',
      'consecutiveFailures', coalesce(v_github_failures, 0),
      'stale', v_github_fetched_at IS NULL OR v_github_fetched_at < v_now - interval '24 hours'
    ));
  END IF;

  FOR v_alert IN SELECT value FROM pg_catalog.jsonb_array_elements(v_alerts)
  LOOP
    v_code := v_alert ->> 'code';
    v_codes := pg_catalog.array_append(v_codes, v_code);
    INSERT INTO private.backend_alert_state (
      alert_code, active, consecutive_observations,
      first_observed_at, last_observed_at, resolved_at, updated_at
    ) VALUES (
      v_code, true, 1, v_now, v_now, NULL, v_now
    )
    ON CONFLICT (alert_code) DO UPDATE
    SET active = true,
        consecutive_observations = CASE
          WHEN private.backend_alert_state.active
            THEN private.backend_alert_state.consecutive_observations + 1
          ELSE 1
        END,
        first_observed_at = CASE
          WHEN private.backend_alert_state.active
            THEN private.backend_alert_state.first_observed_at
          ELSE v_now
        END,
        last_observed_at = v_now,
        last_notified_at = CASE
          WHEN private.backend_alert_state.active
            THEN private.backend_alert_state.last_notified_at
          ELSE NULL
        END,
        resolved_at = NULL,
        updated_at = v_now;
  END LOOP;

  UPDATE private.backend_alert_state AS state
  SET active = false,
      consecutive_observations = 0,
      resolved_at = v_now,
      updated_at = v_now
  WHERE state.active
    AND NOT (state.alert_code = ANY(v_codes));

  SELECT coalesce(pg_catalog.array_agg(state.alert_code ORDER BY state.alert_code), ARRAY[]::text[])
  INTO v_notification_codes
  FROM private.backend_alert_state AS state
  WHERE state.active
    AND (state.last_notified_at IS NULL OR state.last_notified_at < v_now - interval '1 hour');

  RETURN pg_catalog.jsonb_build_object(
    'generatedAt', v_now,
    'windowMinutes', p_window_minutes,
    'alerts', v_alerts,
    'notificationCodes', pg_catalog.to_jsonb(v_notification_codes),
    'summary', pg_catalog.jsonb_build_object(
      'aiFinalizationFailures', v_ai_failures,
      'commentRequests', v_comment_total,
      'commentFailures', v_comment_failures,
      'commentDeadlocks', v_comment_deadlocks,
      'shareReads', v_share_total,
      'shareFailures', v_share_failures,
      'maintenanceFailures', v_maintenance_failures,
      'maintenanceFailureStreak', CASE WHEN v_maintenance_failure_streak THEN 1 ELSE 0 END,
      'cronFailures', v_cron_failures,
      'cronFailureStreak', CASE WHEN v_cron_failure_streak THEN 1 ELSE 0 END,
      'staleEdgeDispatches', v_stale_edge_dispatches,
      'expiredPendingAiRequests', v_expired_pending
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_backend_alert_delivery_v1(
  p_alert_codes text[]
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_updated integer;
BEGIN
  IF p_alert_codes IS NULL
     OR pg_catalog.cardinality(p_alert_codes) < 1
     OR pg_catalog.cardinality(p_alert_codes) > 32
     OR EXISTS (
       SELECT 1
       FROM pg_catalog.unnest(p_alert_codes) AS code(value)
       WHERE code.value !~ '^[a-z][a-z0-9_]{0,63}$'
     ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid alert codes';
  END IF;

  UPDATE private.backend_alert_state AS state
  SET last_notified_at = pg_catalog.now(),
      updated_at = pg_catalog.now()
  WHERE state.active
    AND state.alert_code = ANY(p_alert_codes);
  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated;
END;
$$;

REVOKE ALL ON FUNCTION private.preview_backend_transient_cleanup_v1(integer)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.cleanup_backend_transient_data_v1(integer)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.run_ai_reconciliation_job_v1(integer)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.set_backend_maintenance_flags_v1(boolean, boolean)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.invoke_backend_edge_job_v1(text)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.reconcile_backend_edge_dispatches_v1(integer)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.evaluate_backend_ops_alerts_v1(integer)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.ack_backend_alert_delivery_v1(text[])
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.evaluate_backend_ops_alerts_v1(integer)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_backend_alert_delivery_v1(text[])
  TO service_role;

DO $$
DECLARE
  v_job_id bigint;
BEGIN
  FOR v_job_id IN
    SELECT jobs.jobid
    FROM cron.job AS jobs
    WHERE jobs.jobname IN (
      'resume-backend-ai-reconcile',
      'resume-backend-edge-dispatch-reconcile',
      'resume-backend-transient-cleanup',
      'resume-backend-transient-catchup',
      'resume-backend-ops-monitor',
      'resume-github-stars-refresh'
    )
  LOOP
    PERFORM cron.unschedule(v_job_id);
  END LOOP;

  PERFORM cron.schedule(
    'resume-backend-ai-reconcile',
    '*/5 * * * *',
    $job$SELECT private.run_ai_reconciliation_job_v1(200);$job$
  );
  PERFORM cron.schedule(
    'resume-backend-edge-dispatch-reconcile',
    '* * * * *',
    $job$SELECT private.reconcile_backend_edge_dispatches_v1(200);$job$
  );
  PERFORM cron.schedule(
    'resume-backend-transient-cleanup',
    '17 * * * *',
    $job$SELECT private.cleanup_backend_transient_data_v1(1000);$job$
  );
  PERFORM cron.schedule(
    'resume-backend-transient-catchup',
    '42 3 * * *',
    $job$SELECT private.cleanup_backend_transient_data_v1(5000);$job$
  );
  PERFORM cron.schedule(
    'resume-backend-ops-monitor',
    '*/5 * * * *',
    $job$SELECT private.invoke_backend_edge_job_v1('backend-ops-monitor');$job$
  );
  PERFORM cron.schedule(
    'resume-github-stars-refresh',
    '11 */6 * * *',
    $job$SELECT private.invoke_backend_edge_job_v1('github-stars-refresh');$job$
  );
END;
$$;
