CREATE TABLE public.ats (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  resume_id uuid NOT NULL,
  user_id uuid DEFAULT auth.uid(),
  version text,
  meta jsonb,
  "readabilityIndex" jsonb,
  "fixChecklist" jsonb[],
  summary jsonb,
  scores jsonb,
  findings jsonb,
  todo_items jsonb[] DEFAULT '{}'::jsonb[],
  CONSTRAINT ats_pkey PRIMARY KEY (id),
  CONSTRAINT ats_resume_id_fkey
    FOREIGN KEY (resume_id) REFERENCES public.resume_config (resume_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT ats_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);
