CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.update_updated_at_column()
  FROM PUBLIC, anon, authenticated;

CREATE TABLE public.resume_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL DEFAULT auth.uid(),
  type text DEFAULT 'default',
  basics jsonb,
  job_intent jsonb,
  application_info jsonb,
  edu_background jsonb,
  work_experience jsonb,
  internship_experience jsonb,
  campus_experience jsonb,
  project_experience jsonb,
  skill_specialty jsonb,
  honors_certificates jsonb,
  self_evaluation jsonb,
  hobbies jsonb,
  "order" jsonb DEFAULT '["basics", "jobIntent", "applicationInfo", "eduBackground", "workExperience", "internshipExperience", "campusExperience", "projectExperience", "skillSpecialty", "honorsCertificates", "selfEvaluation", "hobbies"]'::jsonb,
  visibility jsonb,
  updated_at timestamptz DEFAULT now(),
  display_name text DEFAULT '简历',
  description text,
  resume_id uuid NOT NULL DEFAULT gen_random_uuid(),
  automerge_enabled boolean DEFAULT true,
  document_version integer DEFAULT 1,
  CONSTRAINT resume_config_pkey PRIMARY KEY (id),
  CONSTRAINT resume_config_resume_id_key UNIQUE (resume_id),
  CONSTRAINT resume_config_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

CREATE INDEX idx_resume_config_automerge
  ON public.resume_config (automerge_enabled)
  WHERE automerge_enabled = true;

CREATE TRIGGER update_resume_config_updated_at
  BEFORE UPDATE ON public.resume_config
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
